# Generated by Django 3.2.6 on 2022-01-03 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_add_trashed_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeloUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='openid')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'felo用户数据',
                'verbose_name_plural': 'felo用户数据',
                'db_table': 'oauth_felo',
            },
        ),
    ]
